changelog:
  exclude:
    labels:
      - "ignore for release"

  categories:
    - title: Breaking Changes
      labels: ["Type: Breaking Change", "breaking change"]
    - title: Bug Fixes
      labels: ["Type: bug", "bug"]
    - title: Documentation
      labels: ["Type: Documentation", "documentation"]
    - title: CI
      labels: ["Type: CI", "ci"]
    - title: Security Fixes
      labels: ["Type: Security", "security"]
    - title: Dependency Updates
      labels: ["Type: Dependencies", "dependencies"]
    - title: Other Changes
      labels: ["*"]
